;;; lsp-scheme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from lsp-scheme.el

(autoload 'lsp-scheme-chicken "lsp-scheme" "\
Register CHICKEN's LSP server if needed.")
(autoload 'lsp-scheme-gambit "lsp-scheme" "\
Register Guile's LSP server if needed.")
(autoload 'lsp-scheme-guile "lsp-scheme" "\
Regist Guile's LSP server if needed.")
(autoload 'lsp-scheme "lsp-scheme" "\
Setup and start Scheme's LSP server.")
(register-definition-prefixes "lsp-scheme" '("lsp-scheme-"))

;;; End of scraped data

(provide 'lsp-scheme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-scheme-autoloads.el ends here
