;;; sudoku-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sudoku.el

(autoload 'sudoku "sudoku" "\
Start playing sudoku.
Avoid selecting already solved puzzle unless prefix ARG is specified.

(fn &optional ARG)" t)
(register-definition-prefixes "sudoku" '("sudoku-"))

;;; End of scraped data

(provide 'sudoku-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sudoku-autoloads.el ends here
