;;; jq-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from jq-ts-mode.el

(autoload 'jq-ts-mode "jq-ts-mode" "\
Major mode for editing jq buffers.

\\<jq-ts-mode-map>

(fn)" t)
(register-definition-prefixes "jq-ts-mode" '("jq-ts-mode-"))

;;; End of scraped data

(provide 'jq-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jq-ts-mode-autoloads.el ends here
